from typing import Dict, List

INTENT_SENTENCES: Dict[str, List[str]] = {
    'coding': [
        # --- Basi di Programmazione e Scripting ---
        "Scrivi il codice sorgente per eseguire questa operazione.",
        "Fammi un programma in Python che automatizza questo processo.",
        "Come si scrive questa funzione in JavaScript o TypeScript?",
        "Sviluppa uno script che elabora e trasforma questi file di testo.",
        "Mostrami come implementare una hashmap o un dizionario in codice.",
        "Scrivi una classe orientata agli oggetti con ereditarietà e polimorfismo.",
        "Qual è la differenza tra passaggio di parametri per valore e per riferimento?",
        "Spiega le differenze tra let, const e var in JavaScript.",
        "Crea una regular expression (regex) per validare un indirizzo email o un URL.",
        "Come utilizzo i puntatori e l'allocazione dinamica della memoria in C++?",
        "Spiegami la differenza tra multithreading e programmazione asincrona.",
        "Come avvio un thread o un processo separato in Java o C#?",
        "Come si usa il costrutto switch-case per valutare molteplici clausole all'interno di un codice in C#?",
        "Sviluppa un modulo riutilizzabile in Python seguendo le best practice di packaging.",
        "Implementa un sistema di gestione delle eccezioni personalizzate in Ruby.",
        
        # --- Calcolo Numerico e Ricerca Operativa (Implementazione) ---
        "Scrivi uno script Python che utilizza il metodo di Newton-Raphson per trovare le radici di un polinomio.",
        "Implementa l'algoritmo del simplesso in C++ per risolvere problemi di programmazione lineare.",
        "Codice per calcolare la fattorizzazione LU di una matrice sparsa di grandi dimensioni.",
        "Sviluppa una funzione per l'integrazione numerica usando il metodo di Simpson o dei trapezi.",
        "Implementa un algoritmo di ottimizzazione genetica per risolvere il problema del commesso viaggiatore.",
        "Scrivi uno script per la risoluzione numerica di equazioni differenziali col metodo di Runge-Kutta.",
        "Codice per implementare la Trasformata di Fourier Veloce (FFT) in Java senza librerie esterne.",
        "Sviluppa un simulatore Monte Carlo per modellare processi stocastici in Python.",
        "Implementa l'algoritmo di Dijkstra per trovare il cammino minimo in un grafo pesato.",
        "Scrivi il codice per risolvere un sistema di equazioni lineari usando il metodo di Jacobi o Gauss-Seidel.",
        "Implementa la scomposizione ai valori singolari (SVD) in codice Python per la riduzione della dimensionalità.",
        "Sviluppa un algoritmo di programmazione dinamica per ottimizzare l'allocazione delle risorse in un processo.",
        "Scrivi il codice sorgente per una simulazione di fluidodinamica computazionale bidimensionale.",
        
        # --- Frontend e Web Development ---
        "Crea un componente React che gestisce uno stato globale usando la Context API.",
        "Come si centra un div verticalmente e orizzontalmente usando CSS Flexbox o Grid?",
        "Scrivi una funzione JavaScript per manipolare il DOM e aggiungere un elemento HTML.",
        "Spiegami il ciclo di vita di un componente in Vue.js o React.",
        "Implementa un hook personalizzato in React per gestire il fetch dei dati.",
        "Come configuro Webpack e Babel per un progetto di frontend moderno?",
        "Gestisci gli eventi di click e hover del mouse in un file TypeScript.",
        "Scrivi il codice per un'animazione CSS fluida usando i keyframes.",
        "Come faccio a passare i props da un componente padre a un figlio in React?",
        "Implementa il routing lato client per una single page application usando React Router.",
        "Spiegami come funziona il Virtual DOM rispetto al DOM reale del browser.",
        "Sviluppa un'interfaccia utente reattiva usando Tailwind CSS e componenti Next.js.",
        "Implementa la gestione degli stati complessi in un'app React tramite Redux Toolkit.",
        "Scrivi il codice per il lazy loading delle immagini in una pagina web ad alte prestazioni.",
        "Sviluppa un'applicazione web progressiva (PWA) con Service Workers per l'accesso offline.",
        "Configura il rendering lato server (SSR) per un'applicazione frontend moderna.",
        
        # --- Backend, API e Server ---
        "Spiegami la differenza tra promise e async/await in JavaScript con un esempio pratico di codice.",
        "Crea un server backend usando Node.js e il framework Express.",
        "Come gestisco l'autenticazione tramite token JWT in un'API REST?",
        "Scrivi un endpoint in Django o Flask che accetta richieste POST in formato JSON.",
        "Implementa un middleware in Python per il logging delle richieste HTTP.",
        "Spiegami le differenze principali tra un'architettura API RESTful e GraphQL.",
        "Codice Java per creare un'applicazione Spring Boot con un controller REST.",
        "Risolvi l'errore CORS (Cross-Origin Resource Sharing) quando il frontend chiama il backend.",
        "Come si implementa la paginazione dei risultati in un endpoint API?",
        "Qual è il modo migliore per gestire le variabili d'ambiente in un progetto backend?",
        "Codice per effettuare una chiamata HTTP GET usando la libreria requests in Python.",
        "Come estraggo dati da una pagina HTML facendo web scraping con BeautifulSoup o Puppeteer?",
        "Configura una connessione gRPC tra due microservizi scritti in Go.",
        "Implementa il meccanismo di rate limiting per proteggere le tue API in Node.js.",
        "Scrivi uno script Node.js per elaborare stream di dati binari e salvarli su file.",
        "Sviluppa un sistema di code di messaggi (message broker) usando RabbitMQ o Kafka in Python.",
        
        # --- Database e SQL ---
        "Scrivi una query SQL con costrutti INNER JOIN e GROUP BY.",
        "Come creo un indice su una tabella PostgreSQL per ottimizzare i tempi di lettura?",
        "Spiega la differenza strutturale tra un database relazionale SQL e uno NoSQL come MongoDB.",
        "Scrivi il codice per connettere in modo sicuro un'app Python a un database MySQL.",
        "Implementa una migrazione dello schema del database usando Entity Framework.",
        "Crea uno schema Mongoose per salvare documenti e oggetti JSON in MongoDB.",
        "Scrivi una stored procedure e un trigger in SQL Server.",
        "Come evito la vulnerabilità di SQL injection quando passo parametri utente a una query?",
        "Usa un ORM come SQLAlchemy o Prisma per fare una query sul database senza scrivere SQL.",
        "Configura un sistema di caching distribuito usando Redis in un'app Python.",
        "Scrivi una query MongoDB complessa usando l'aggregation framework.",
        "Implementa la logica di replica e sharding per un database Cassandra.",
        "Ottimizza lo schema del database per supportare query analitiche (OLAP) in tempo reale.",
        
        # --- DevOps, Git, Docker e OS ---
        "Qual è il comando Git per fare il merge di un branch ed evitare un fast-forward?",
        "Spiegami passo passo come risolvere un merge conflict su GitHub o GitLab.",
        "Scrivi un file Dockerfile per containerizzare un'applicazione Node.js in produzione.",
        "Scrivi uno script in Bash che cancelli in modo sicuro i file di log da terminale.",
        "Configura una pipeline di CI/CD per il deploy automatico usando GitHub Actions.",
        "Quali sono i comandi per fermare e riavviare un demone systemd in Linux?",
        "Spiega la differenza prestazionale tra un container Docker e una macchina virtuale.",
        "Scrivi uno script PowerShell per rinominare file in massa all'interno di una cartella.",
        "Come faccio un rebase interattivo dei miei commit in un repository Git?",
        "Scrivimi un file docker-compose.yml per il deploy di un server web nginx e database.",
        "Come configuro un cluster Kubernetes per gestire il bilanciamento del carico tra i pod in produzione?",
        "Scrivi uno script Bash per calcolare il TFR o altre voci contabili automatizzando i report.",
        "Configura un reverse proxy con Nginx per gestire il traffico SSL/TLS.",
        "Crea uno script di automazione per il backup periodico del database su Amazon S3.",
        "Sviluppa una configurazione Terraform per istanziare macchine virtuali su Azure o AWS.",
        "Scrivi uno script in Python per monitorare l'utilizzo della CPU e della memoria del server in tempo reale.",
        
        # --- Cybersecurity e Crittografia Applicata ---
        "Implementa l'algoritmo di crittografia RSA in Python per cifrare messaggi di testo.",
        "Scrivi il codice per generare un hash sicuro di una password usando bcrypt o argon2.",
        "Sviluppa una funzione per la verifica delle firme digitali usando chiavi asimmetriche.",
        "Codice per implementare lo scambio di chiavi Diffie-Hellman in un'app di chat.",
        "Scrivi uno script per rilevare tentativi di brute force analizzando i file di log del server.",
        "Implementa un sistema di crittografia end-to-end per la trasmissione di dati JSON.",
        "Crea una funzione JavaScript che implementa il protocollo OAuth2 per l'autorizzazione.",
        "Scrivi il codice sorgente per un generatore di token di sessione sicuri e casuali.",
        
        # --- ML/AI, Data Science e Automazione ---
        "Scrivi il codice per l'addestramento di una rete neurale convoluzionale usando PyTorch.",
        "Implementa un modello di regressione lineare da zero usando solo la libreria NumPy.",
        "Scrivi uno script Python che anonimizza i dati di un database SQL per la conformità GDPR.",
        "Codice per visualizzare i risultati di un'analisi dati usando Matplotlib o Seaborn.",
        "Sviluppa una pipeline di pre-processing dei dati per pulire dataset in formato CSV.",
        "Implementa un algoritmo di clustering K-means in Python per segmentare i dati.",
        "Scrivi il codice per il fine-tuning di un modello Transformer usando la libreria HuggingFace.",
        "Crea una funzione per il calcolo della similarità coseno tra due vettori densi in Python.",
        "Sviluppa uno script per l'estrazione di feature testuali (TF-IDF) da un dataset di documenti.",
        
        # --- Low-Level e Sistemi Embedded ---
        "Scrivi il codice assembly per eseguire una somma tra registri in architettura x86.",
        "Sviluppa un semplice driver per il kernel Linux che scrive messaggi nel buffer di log.",
        "Implementa la gestione degli interrupt hardware in codice C per un microcontrollore Arduino.",
        "Scrivi il codice per comunicare con un sensore tramite protocollo I2C o SPI in C++.",
        "Sviluppa un gestore di memoria custom per allocare blocchi di dati a dimensione fissa.",
        
        # --- Debugging, Errori e Testing ---
        "Correggi questo bug nel codice sorgente e rimuovi gli errori di compilazione.",
        "Come faccio il debug di questa eccezione o runtime error nel mio programma?",
        "Scrivi uno unit test in Python utilizzando la libreria pytest o unittest.",
        "Spiegami come leggere correttamente uno stack trace per rintracciare un'eccezione in Java.",
        "Come trovo e risolvo un memory leak in un'applicazione Node.js in produzione?",
        "Aggiungi blocchi try-catch-finally per gestire in sicurezza le eccezioni in questo blocco di codice.",
        "Implementa un test di integrazione per verificare la comunicazione tra frontend e API.",
        "Scrivi il codice per il profiling delle prestazioni e l'analisi del consumo di memoria in C#.",
        "Sviluppa un sistema di mock per simulare le risposte di un servizio esterno nei test Jest."
    ],
    
    'math': [
        # --- Analisi Matematica 1 (Limiti, Serie, Derivate, Integrali) ---
        "Calcola il limite per x che tende a infinito di questa funzione razionale.",
        "Qual è la derivata prima e seconda di questa funzione trigonometrica?",
        "Trova l'equazione della retta tangente al grafico della funzione nel punto x0.",
        "Applica il teorema di de L'Hôpital per risolvere questa forma indeterminata 0/0.",
        "Trova gli asintoti obliqui, orizzontali e verticali di questa funzione iperbolica.",
        "Dimostra che la funzione è continua e derivabile in tutto il suo dominio di definizione.",
        "Trova i punti di massimo relativo, minimo assoluto e flesso studiando il segno della derivata.",
        "Sviluppa questa funzione in serie di Taylor o Maclaurin centrata nell'origine.",
        "Studia il carattere della serie numerica usando il criterio del rapporto o della radice.",
        "Determina il raggio di convergenza e l'intervallo di questa serie di potenze.",
        "Applica il teorema di Rolle, Lagrange o Cauchy per dimostrare l'enunciato.",
        "Determina la convergenza di una serie a termini positivi tramite il criterio del confronto asintotico.",
        "Verifica l'uniforme continuità di una funzione su un intervallo limitato tramite il teorema di Heine-Cantor.",
        "Calcola l'integrale indefinito applicando il metodo di integrazione per parti.",
        "Calcola l'integrale definito tra zero e pi greco della funzione seno al quadrato.",
        "Usa il metodo di sostituzione per risolvere questo integrale irrazionale.",
        "Applica la scomposizione in fratti semplici per integrare la funzione razionale fratta.",
        "Studia la derivabilità di una funzione definita a tratti verificando il limite del rapporto incrementale.",
        "Calcola il valore di un limite complesso utilizzando gli sviluppi asintotici di Landau (o-piccolo).",
        "Determina la classe di regolarità C^n di una funzione in un intorno di un punto critico.",

        # --- Analisi Matematica 2 e 3 (Multivariabile, Misura, Funzionale) ---
        "Risolvi l'integrale doppio sul dominio D delimitato dalle circonferenze.",
        "Calcola l'integrale triplo passando alle coordinate sferiche o cilindriche.",
        "Dimostra la convergenza dell'integrale improprio utilizzando i criteri del confronto.",
        "Determina il piano tangente alla superficie nel punto di coordinate fornite.",
        "Calcola il rotore e la divergenza del campo vettoriale nello spazio R3.",
        "Verifica se il campo vettoriale è conservativo trovandone il potenziale scalare.",
        "Applica il teorema di Stokes per calcolare la circuitazione lungo la curva chiusa.",
        "Usa il teorema della divergenza (Gauss) per calcolare il flusso attraverso la superficie.",
        "Trova i massimi e minimi vincolati della funzione utilizzando il metodo dei moltiplicatori di Lagrange.",
        "Calcola l'integrale di linea di prima o seconda specie lungo la curva parametrizzata.",
        "Dimostra la completezza dello spazio Lp rispetto alla norma della convergenza in media.",
        "Enuncia il teorema di rappresentazione di Riesz per i funzionali lineari in uno spazio di Hilbert.",
        "Studia la convergenza debole e forte di una successione di elementi in uno spazio di Banach.",
        "Calcola la trasformata di Fourier o di Laplace nel senso delle distribuzioni temperate.",
        "Definisci la misura di Lebesgue e spiega la differenza con l'integrale di Riemann.",
        "Determina la norma di un operatore lineare limitato tra due spazi vettoriali normati.",

        # --- Algebra Lineare e Calcolo Matriciale ---
        "Calcola il determinante e la traccia di questa matrice quadrata 3x3.",
        "Trova gli autovalori e i relativi autovettori associati alla matrice fornita.",
        "Dimostra che questi vettori formano una base ortogonale per lo spazio vettoriale R3.",
        "Applica il processo di ortogonalizzazione di Gram-Schmidt a questo set di vettori.",
        "Risolvi il sistema lineare omogeneo associato usando il metodo di eliminazione di Gauss-Jordan.",
        "Determina la matrice inversa usando il metodo dei cofattori o la matrice aggiunta.",
        "Verifica se la matrice è diagonalizzabile confrontando la molteplicità algebrica e geometrica.",
        "Trova il nucleo (kernel) e l'immagine di questa applicazione o trasformazione lineare.",
        "Calcola il prodotto matriciale tra matrici non quadrate e verificane la compatibilità dimensionale.",
        "Determina il rango di una matrice al variare di un parametro reale tramite il teorema di Kronecker.",
        "Applica la decomposizione QR o la scomposizione ai valori singolari (SVD) a una matrice rettangolare.",
        "Risolvi un sistema lineare sovradeterminato utilizzando il metodo dei minimi quadrati.",
        "Verifica se una forma quadratica è definita positiva analizzando i segni dei minori principali (Criterio di Sylvester).",
        "Calcola la matrice di passaggio tra due basi diverse dello stesso spazio vettoriale.",
        "Dimostra che il prodotto di due matrici ortogonali è ancora una matrice ortogonale.",

        # --- Geometria (Euclidea, Proiettiva, Differenziale) ---
        "Trova l'equazione del piano passante per tre punti non allineati nello spazio cartesiano.",
        "Determina le coordinate del fuoco, la direttrice e l'eccentricità di questa parabola.",
        "Trasforma questa equazione cartesiana nelle equivalenti coordinate polari.",
        "Calcola la distanza minima tra un punto e una retta o tra due piani sghembi.",
        "Studia la classificazione delle coniche nel piano proiettivo utilizzando la matrice associata.",
        "Determina le coordinate omogenee di un punto all'infinito (punto improprio) nel piano.",
        "Calcola la curvatura gaussiana e la curvatura media di una superficie parametrizzata.",
        "Trova le geodetiche su una superficie di rotazione applicando le equazioni di Eulero-Lagrange.",
        "Spiega la dualità tra punti e rette nel contesto della geometria proiettiva.",
        "Determina l'area di un triangolo sferico utilizzando il teorema di Gauss-Bonnet.",
        "Verifica se due rette nello spazio sono parallele, incidenti o sghembe.",

        # --- Probabilità e Statistica ---
        "Calcola la probabilità condizionata dell'evento A sapendo che si è verificato B col teorema di Bayes.",
        "Determina il valore atteso (media), la varianza e la deviazione standard della distribuzione.",
        "Calcola l'intervallo di confidenza al 95% per la stima della media di una popolazione normale.",
        "Enuncia e spiega il teorema del limite centrale e la legge dei grandi numeri.",
        "Costruisci la funzione di ripartizione e di densità per questa variabile aleatoria continua.",
        "Risolvi il test d'ipotesi z o t-test calcolando il p-value e stabilendo la regione di rifiuto.",
        "Spiega la differenza teorica tra la distribuzione di Poisson e la distribuzione binomiale.",
        "Determina l'efficienza di uno stimatore calcolando il limite inferiore di Cramér-Rao.",
        "Esegui un test del chi-quadrato per verificare l'indipendenza tra due variabili categoriche.",
        "Calcola la retta di regressione lineare minimizzando la somma dei quadrati dei residui.",
        "Definisci la funzione caratteristica di una variabile aleatoria e spiegane l'utilità nei calcoli.",

        # --- Equazioni Differenziali e Fisica Matematica ---
        "Risolvi l'equazione differenziale lineare del secondo ordine a coefficienti costanti.",
        "Trova l'integrale generale dell'equazione differenziale omogenea associata.",
        "Risolvi il problema di Cauchy determinando la soluzione particolare dell'equazione.",
        "Integra l'equazione differenziale del primo ordine a variabili separabili mostrando i passaggi.",
        "Calcola la trasformata di Laplace di questa funzione a gradino o impulso di Dirac.",
        "Studia la stabilità dei punti di equilibrio di un sistema dinamico lineare tramite gli autovalori.",
        "Risolvi l'equazione del calore o delle onde utilizzando il metodo di separazione delle variabili.",
        "Determina la soluzione di un'equazione differenziale esatta trovandone il fattore integrante.",

        # --- Logica, Algebra Astratta e Teoria dei Numeri ---
        "Dimostra per induzione matematica che questa proposizione logica è vera per ogni naturale n.",
        "Dimostra per assurdo l'irrazionalità della radice quadrata del numero due.",
        "Dimostra che l'insieme dei numeri reali non è numerabile applicando l'argomento diagonale di Cantor.",
        "Spiega il teorema di incompletezza di Gödel e perché ha sconvolto i fondamenti della logica formale.",
        "Applica l'algoritmo euclideo delle divisioni successive per calcolare il massimo comun divisore.",
        "Risolvi la congruenza lineare modulo m usando i principi dell'aritmetica modulare.",
        "Verifica se l'insieme fornito costituisce un gruppo abeliano rispetto all'operazione data.",
        "Definisci i concetti di omomorfismo e isomorfismo tra due strutture algebriche o anelli.",

        # --- Anti-trappola ed Edge Cases ---
        "Quali sono gli autovalori e gli autovettori della matrice identità 3x3?",
        "Descrivi la teoria del calcolo matriciale necessaria per definire un prodotto tra tensori.",
        "Spiegami la derivazione matematica della formula del TFR stabilita dalla legge.",
        "Analizza la struttura logica e le equazioni necessarie per descrivere un algoritmo di ricerca."
    ],
    
    'rights': [
        # --- Diritto Costituzionale e Pubblico ---
        "Qual è l'iter legis per l'approvazione di una legge costituzionale da parte del Parlamento?",
        "Spiegami i limiti e i presupposti per l'emanazione di un decreto legge da parte del Governo.",
        "Cosa prevede la Costituzione italiana in merito al conflitto di attribuzione tra poteri dello Stato?",
        "Quali sono le differenze tra regolamento europeo e direttiva nell'ordinamento giuridico?",
        "Spiega il principio di laicità dello Stato e la libertà di culto secondo la Costituzione.",
        "Quali sono le prerogative del Presidente della Repubblica in merito allo scioglimento delle Camere?",
        "Cosa si intende per riserva di legge assoluta e relativa nell'ordinamento costituzionale?",
        "Spiega il funzionamento del referendum abrogativo e il giudizio di ammissibilità della Consulta.",
        "Quali sono i diritti inviolabili dell'uomo sanciti dall'articolo 2 della Costituzione?",
        "Come funziona il sistema di giustizia costituzionale e l'accesso in via incidentale.",

        # --- Diritto Amministrativo ---
        "Come funziona il ricorso gerarchico e il ricorso al TAR nel diritto amministrativo?",
        "Spiega la differenza tra nullità e annullabilità di un provvedimento amministrativo.",
        "Quali sono i requisiti normativi per richiedere la cittadinanza italiana per residenza?",
        "Cosa si intende per silenzio-assenso e silenzio-rifiuto nella pubblica amministrazione?",
        "Quali sono i presupposti giuridici per l'espropriazione per pubblica utilità?",
        "Spiega il principio di trasparenza amministrativa e il diritto di accesso agli atti (Legge 241/90).",
        "Come viene gestita la responsabilità civile della Pubblica Amministrazione verso i cittadini?",
        "Quali sono le fasi del procedimento amministrativo e l'obbligo di motivazione.",
        "Spiega la disciplina dei contratti pubblici e le procedure di gara d'appalto.",

        # --- Diritto Penale e Procedura Penale ---
        "Spiegami la differenza tra dolo eventuale, colpa cosciente e preterintenzione nel codice penale.",
        "Quali sono le esimenti o cause di giustificazione come la legittima difesa e lo stato di necessità?",
        "Quali sono le responsabilità penali dirette dell'amministratore delegato in caso di bancarotta fraudolenta.",
        "Spiega i presupposti giuridici per il reato di diffamazione a mezzo stampa o via web.",
        "Come funziona l'istituto del patteggiamento e in quali casi non può essere richiesto dall'imputato?",
        "Quali sono i termini e i presupposti per la richiesta di una misura cautelare personale.",
        "Cosa si intende per incidente probatorio e quando può essere richiesto nel processo penale?",
        "Spiega il principio di non colpevolezza fino a sentenza definitiva e il favor rei.",
        "Quali sono le differenze tra reati consumati, delitto tentato e desistenza volontaria?",
        "Cosa prevede il codice penale in merito al concorso di persone nel reato.",
        "Spiegami l'istituto della prescrizione del reato e come vengono calcolati i termini.",
        "Quali sono le pene accessorie e le misure di sicurezza previste dall'ordinamento penale?",

        # --- Diritto Civile (Obbligazioni, Contratti, Diritti Reali) ---
        "Quali sono gli elementi essenziali del contratto secondo l'articolo 1325 del codice civile?",
        "Spiega le differenze tra risoluzione per inadempimento, impossibilità sopravvenuta ed eccessiva onerosità.",
        "Quali sono le differenze tra responsabilità contrattuale ed extracontrattuale (art. 2043 c.c.)?",
        "Quali sono le tutele per il consumatore contro le clausole vessatorie secondo il Codice del Consumo?",
        "Cosa prevede la normativa civile per l'acquisto della proprietà tramite usucapione?",
        "Spiega il funzionamento della caparra confirmatoria e della clausola penale nei contratti.",
        "Quali sono i diritti e i doveri derivanti dal contratto di locazione ad uso abitativo?",
        "Come funziona l'azione di rivendicazione a tutela della proprietà privata?",
        "Cosa si intende per obbligazioni pecuniarie e il divieto di anatocismo.",
        "Quali sono i presupposti per la rescissione del contratto per stato di pericolo o bisogno?",

        # --- Diritto di Famiglia e Successioni ---
        "Qual è la procedura legale per la separazione consensuale e il divorzio breve in Italia?",
        "Cosa stabilisce l'ordinamento in merito all'affidamento condiviso e alla responsabilità genitoriale?",
        "Spiegami la differenza tra testamento olografo, pubblico e segreto secondo il codice civile.",
        "Cosa si intende per quota di legittima e chi sono gli eredi legittimari nella successione.",
        "Come funziona l'accettazione dell'eredità con beneficio d'inventario?",
        "Spiega l'istituto dell'amministrazione di sostegno e le differenze con l'interdizione.",
        "Quali sono le conseguenze giuridiche della comunione dei beni rispetto alla separazione dei beni?",
        "Cosa prevede la legge sulle unioni civili e le convivenze di fatto (Legge Cirinnà).",

        # --- Diritto del Lavoro ---
        "Quali sono le tutele legali previste dallo Statuto dei Lavoratori contro il licenziamento discriminatorio?",
        "Spiega la differenza tra licenziamento per giusta causa e giustificato motivo oggettivo.",
        "Quali sono i diritti del lavoratore subordinato in tema di ferie, malattia e permessi retribuiti?",
        "Cosa prevede la giurisprudenza in merito al demansionamento e al mobbing sul posto di lavoro?",
        "Come funziona la disciplina del contratto a tempo determinato e le causali di rinnovo.",
        "Quali sono gli obblighi di sicurezza sul lavoro previsti dal D.Lgs. 81/08?",

        # --- Diritto Commerciale, Societario e Tributario ---
        "Quali sono le differenze di responsabilità tra soci di una S.r.l. e quelli di una S.p.a.?",
        "Spiega il funzionamento dell'assemblea dei soci e le competenze del Consiglio di Amministrazione.",
        "Quali sono i presupposti normativi per la dichiarazione di liquidazione giudiziale (ex fallimento)?",
        "Come si articola il contenzioso tributario e quali sono i gradi di giudizio delle Commissioni Tributarie?",
        "Cosa si intende per elusione fiscale e abuso del diritto secondo la normativa vigente?",
        "Spiega la disciplina della concorrenza sleale e la tutela dei marchi e brevetti.",
        "Quali sono gli obblighi di trasparenza nei bilanci d'esercizio delle società quotate?",

        # --- Diritto Sportivo ---
        "Quali sono le sanzioni previste dal Codice di Giustizia Sportiva per la violazione della lealtà sportiva?",
        "Spiega il funzionamento del DASPO e i poteri del Questore in merito alla sicurezza negli stadi.",
        "Cosa prevede la normativa sul vincolo sportivo e il tesseramento degli atleti dilettanti.",
        "Come si articola il ricorso al Collegio di Garanzia dello Sport presso il CONI?",
        "Spiega la responsabilità oggettiva delle società sportive per il comportamento dei propri tifosi.",
        "Quali sono le norme antidoping previste dal Codice WADA e dal Tribunale Nazionale Antidoping?",

        # --- PONTE SEMANTICO 1: Diritto dell'Informatica (Tech-Law) ---
        "Quali sono gli obblighi legali e le sanzioni del GDPR per la conservazione dei dati in un database?",
        "Cosa prevede la normativa sulla privacy per la cancellazione sicura dei file e il diritto all'oblio?",
        "Quali regole giuridiche deve rispettare un software automatizzato per elaborare dati personali?",
        "Spiega la responsabilità legale del DPO nell'architettura di un sistema informatico aziendale.",
        "Come deve essere strutturato il codice di una app per garantire la conformità alla direttiva ePrivacy?",
        "Qual è la validità probatoria e legale dei file di log generati da un server Linux in un processo?",
        "Cosa succede giuridicamente se un dipendente sottrae il codice sorgente commettendo furto intellettuale?",
        "Quali sono i termini legali e le condizioni standard per la licenza d'uso di un software?",
        "Come si applica la disciplina del diritto d'autore e del copyright al web scraping di siti web?",
        "Come si calcola la prescrizione di un reato informatico o cybercrimine secondo il codice penale?",
        "Quali clausole legali automatiche prevede il diritto civile per l'inadempimento di uno smart contract?",
        "Spiega la disciplina giuridica delle firme elettroniche (semplice, avanzata, qualificata) e del CAD.",

        # --- PONTE SEMANTICO 2: Diritto Finanziario e Calcoli Legali (Math-Law) ---
        "Qual è la formula matematica e legale stabilita dalla normativa per calcolare il TFR netto?",
        "Come si calcola matematicamente il piano di ammortamento alla francese per un mutuo secondo la legge?",
        "Qual è il calcolo legale esatto per la ripartizione millesimale delle spese condominiali del tetto?",
        "Cosa prevede la giurisprudenza per il calcolo dell'anatocismo e degli interessi di mora sui debiti?",
        "Spiegami come si calcolano matematicamente le quote di legittima in una successione complessa.",
        "Quale metodo di calcolo numerico prevede la legge per l'adeguamento ISTAT dell'assegno di mantenimento?",
        "Come si quantifica il danno biologico permanente usando le tabelle del Tribunale di Milano?",
        "Cosa prevede la normativa europea in merito al calcolo del TAEG nei contratti di finanziamento?",
        "Come si calcola l'imposta di registro e l'IVA per la compravendita immobiliare secondo l'erario.",
        "Quali sono i criteri legali per determinare il superamento del tasso soglia dell'usura bancaria?"
    ],
    
    'general': [
        # --- Ricette, Cucina e Istruzioni Procedurali Quotidiane ---
        "Quali sono gli ingredienti e le istruzioni procedurali esatte per preparare il tiramisù perfetto?",
        "Dammi la ricetta tradizionale esatta e i passaggi procedurali per cucinare la carbonara romana.",
        "Quali sono i passaggi passo-passo per preparare una pizza margherita fatta in casa?",
        "Spiegami i procedimenti corretti per la cottura sottovuoto a bassa temperatura della carne.",
        "Dammi le istruzioni dettagliate su come fare il lievito madre partendo da zero.",
        "Qual è la lista della spesa e il procedimento esatto per cucinare una paella valenciana?",
        "Come si prepara un cocktail Mojito perfetto? Dammi dosi e istruzioni.",
        "Quali sono le tecniche culinarie per sfilettare e preparare correttamente il pesce crudo?",
        "Come si prepara un brodo vegetale saporito partendo da verdure fresche?",
        "Quali sono i segreti per ottenere una frittura di pesce croccante e asciutta?",
        "Spiegami come si fa la pasta frolla e quali sono le proporzioni tra burro e farina.",
        
        # --- Vita Quotidiana, Fai-da-Te e Consigli Pratici ---
        "Come faccio a organizzare un viaggio economico di due settimane in Giappone?",
        "Quali sono i migliori consigli e tecniche per gestire lo stress e l'ansia quotidiana?",
        "Dammi delle istruzioni procedurali su come cambiare la ruota forata di un'automobile.",
        "Come si coltivano le piante da appartamento e quanto spesso vanno annaffiate?",
        "Qual è il metodo migliore per pulire le fughe dei pavimenti e rimuovere la muffa?",
        "Spiegami come strutturare un curriculum vitae efficace per trovare lavoro rapidamente.",
        "Quali sono le regole di etichetta e buone maniere per una cena di gala formale?",
        "Dammi dei consigli su come arredare un soggiorno piccolo per ottimizzare gli spazi.",
        "Come si fa la manutenzione ordinaria di una bicicletta da corsa o mountain bike?",
        "Quali sono i passaggi per dipingere una stanza e preparare i muri correttamente?",
        "Come si rimuovono le macchie di vino rosso o caffè dai tessuti delicati?",
        "Quali sono gli attrezzi indispensabili per iniziare a fare piccoli lavori di falegnameria in casa?",
        "Spiegami come montare una mensola a muro usando correttamente i tasselli e il trapano.",
        
        # --- Storia, Geografia e Scienze Umanistiche ---
        "Quali furono le cause economiche e sociali del crollo dell'Impero Romano d'Occidente?",
        "Spiegami le origini e le conseguenze storiche della Prima Guerra Mondiale e del trattato di Versailles.",
        "Come si sviluppò la civiltà egizia lungo il corso del Nilo e quali furono i suoi faraoni?",
        "Quali fattori storici hanno portato alla Rivoluzione Francese del 1789?",
        "Raccontami la storia dell'Impero Ottomano e le ragioni geopolitiche del suo declino.",
        "Chi era Napoleone Bonaparte e qual è stato il suo impatto politico e militare sulla storia europea?",
        "Quali sono i confini geografici, il clima e le caratteristiche demografiche del continente asiatico?",
        "Spiegami la differenza tra la geografia fisica e la geografia politica dell'Africa.",
        "Quali sono state le conseguenze politiche e sociali dell'introduzione del suffragio universale in Italia?",
        "Raccontami la biografia di Giulio Cesare e il passaggio dalla Repubblica all'Impero Romano.",
        "Spiegami le tappe fondamentali della colonizzazione delle Americhe e l'impatto sui popoli nativi.",
        "Quali sono le principali catene montuose del mondo e come influenzano il clima locale?",
        "Raccontami la storia della Guerra Fredda e il ruolo della cortina di ferro in Europa.",
        
        # --- Filosofia, Letteratura e Arti ---
        "Spiegami la filosofia stoica di Seneca e Marco Aurelio e i suoi principi fondamentali sulla vita.",
        "Qual è la differenza concettuale tra etica deontologica di Kant e l'utilitarismo di Mill?",
        "Cosa intendeva Platone con la sua teoria delle idee e il mito della caverna?",
        "Come si differenziano le grandi correnti del pensiero filosofico orientale dal pensiero occidentale?",
        "Spiegami i temi principali, i personaggi e la struttura della Divina Commedia di Dante Alighieri.",
        "Quali sono le caratteristiche principali del Romanticismo letterario europeo e i suoi autori?",
        "Come si distingue il periodo Barocco dal Rinascimento nell'arte e nell'architettura italiana?",
        "Fai un'analisi dell'opera pittorica 'La Gioconda' di Leonardo da Vinci.",
        "Qual è il significato allegorico del romanzo '1984' di George Orwell?",
        "Spiega le differenze stilistiche tra la musica classica di Mozart e quella di Beethoven.",
        "Quali sono gli elementi chiave della tragedia greca e il concetto di catarsi in Aristotele?",
        "Spiegami l'importanza del Futurismo nell'arte del Novecento e i suoi esponenti principali.",
        "Qual è la trama e il significato del romanzo 'I Promessi Sposi' di Alessandro Manzoni?",
        
        # --- Scienze Generali, Natura e Astronomia ---
        "Come funziona la fotosintesi clorofilliana nelle piante a foglia larga e negli alberi?",
        "Spiega il meccanismo dell'evoluzione darwiniana, la genetica e la selezione naturale.",
        "Come funziona il sistema immunitario umano in risposta a un'infezione batterica o virale?",
        "Cosa sono le cellule staminali e come vengono utilizzate nella medicina moderna rigenerativa?",
        "Spiegami la formazione dei buchi neri supermassicci e i concetti base dell'astronomia.",
        "Come funziona il ciclo dell'acqua sulla Terra e quali sono le sue fasi meteorologiche?",
        "Spiegami la struttura del sistema solare, i pianeti terrestri e i giganti gassosi.",
        "Qual è la differenza biologica tra un virus, un batterio e un fungo patogeno?",
        "Come si formano i terremoti e i vulcani secondo la teoria della tettonica a placche?",
        "Spiega il paradosso del gatto di Schrödinger e le sue implicazioni base per capire i quanti.",
        "Come si applicano i principi della termodinamica per raffreddare un motore a combustione interna?",
        "Quali sono le caratteristiche fisiche della Luna e come influenzano le maree terrestri?",
        "Spiegami come funziona il sistema nervoso centrale e la trasmissione degli impulsi neuronali.",
        "Cosa sono gli esopianeti e quali sono i metodi attuali per scoprirli nello spazio?",

        # --- Benessere, Sport e Tempo Libero ---
        "Quali sono i benefici della meditazione mindfulness per la salute mentale a lungo termine?",
        "Dammi una routine di esercizi di stretching da fare a casa per migliorare la flessibilità.",
        "Spiegami le regole fondamentali del tennis e come funziona il punteggio dei set.",
        "Quali sono le differenze tra lo yoga Hatha e lo yoga Vinyasa?",
        "Come si gioca a pallavolo? Spiegami i ruoli dei giocatori in campo e i falli principali.",
        "Quali sono i principi di una dieta equilibrata per chi pratica sport a livello amatoriale?",
        "Spiegami le regole del fuorigioco nel calcio moderno e come interviene il VAR durante la partita.",
        "Quali sono i fondamenti e le regole ufficiali per giocare a scacchi in modo competitivo?",
        "Dammi dei consigli su come iniziare a correre (running) evitando infortuni alle ginocchia.",
        "Come si organizza un allenamento funzionale a corpo libero per aumentare la forza?",
        
        # --- Società, Cultura Pop e Attualità ---
        "Quali sono i pro e i contro psicologici e sociali di vivere in una grande metropoli rispetto alla campagna?",
        "Come influisce il cambiamento climatico sugli ecosistemi globali e sull'economia moderna?",
        "Quali sono le principali cause storiche e attuali della disuguaglianza economica nel mondo?",
        "Raccontami la trama, l'ambientazione e la lore della saga cinematografica di Star Wars.",
        "Quali sono le differenze tra le varie generazioni sociologiche come Boomer, Millennial e Gen Z?",
        "Come funziona il mercato azionario e quali sono i concetti base per chi vuole iniziare a investire?",
        "Quali sono i generi musicali più popolari del ventesimo secolo e come sono nati?",
        "Spiegami il fenomeno della globalizzazione e l'impatto dei social media sulla comunicazione di massa.",
        "Qual è l'impatto della musica streaming (Spotify, Apple Music) sull'industria discografica?",
        "Quali sono stati i film più premiati nella storia degli Oscar e perché sono considerati dei capolavori?",
        "Spiegami il concetto di economia circolare e come può ridurre l'impatto ambientale dei rifiuti.",
        "Quali sono i principali festival culturali e musicali nel mondo che vale la pena visitare?",
        "Come è cambiata la televisione con l'avvento delle piattaforme di streaming come Netflix?",
        "Spiega l'evoluzione dei videogiochi dalle sale arcade fino alle console di ultima generazione."
    ]

}